#Tomcat 服务
server:
  port: 8080
###ThymeLeaf配置
spring:
  application:
    name: springboot-thymeleaf
  thymeleaf:
    cache: false                   # 开发时关闭缓存,不然没法看到实时页面
    check-template: true
    check-template-location: true
    content-type: text/html
    enabled: true
    #编码 可不用配置
    encoding: UTF-8
    excluded-view-names: ''
    #模板的模式，支持 HTML, XML TEXT JAVASCRIPT
    mode: HTML5                     # 用非严格的 HTML
    prefix: classpath:/WEB-INF/views/
    suffix: .html
    #内容类别,可不用配置
    servlet:
      content-type: text/html